# Generated by Django 6.0.5 on 2026-09-27 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('layer_down', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_above', to='dm_site_app.locations', verbose_name='Vrstva pod')),
                ('layer_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations_below', to='dm_site_app.locations', verbose_name='Vrstva nad')),
            ],
            options={
                'verbose_name': 'Lokace',
                'verbose_name_plural': 'Lokace',
            },
        ),
    ]
