# Generated by Django 6.0.5 on 2026-09-28 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='type',
            field=models.CharField(blank=True, choices=[('continent', 'Kontinent'), ('kingdom', 'Království'), ('region', 'Region'), ('city', 'Město'), ('location', 'Lokace'), ('dungeon', 'Dungeon')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Npc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Jméno')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Muž'), ('female', 'Žena'), ('other', 'Jiné')], max_length=100, null=True, verbose_name='Pohlaví')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npcs', to='dm_site_app.locations', verbose_name='Lokace')),
            ],
            options={
                'verbose_name': 'Npc',
                'verbose_name_plural': 'Npc',
            },
        ),
        migrations.CreateModel(
            name='NpcLoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='Předmět')),
                ('quantity', models.IntegerField(default=1, verbose_name='Počet')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loot_items', to='dm_site_app.npc')),
            ],
            options={
                'verbose_name': 'Loot',
                'verbose_name_plural': 'Loot',
            },
        ),
    ]
