# Generated by Django 6.1.1 on 2026-09-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0002_locations_type_npc_npcloot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompendiumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_index', models.CharField(max_length=100, unique=True, verbose_name='API Index')),
                ('name_cz', models.CharField(max_length=150, verbose_name='Český název')),
                ('name_en', models.CharField(max_length=150, verbose_name='Anglický název')),
                ('category', models.CharField(max_length=100, verbose_name='Kategorie')),
                ('cost_gold', models.IntegerField(default=0, verbose_name='Cena (Zlaťáky)')),
                ('cost_silver', models.IntegerField(default=0, verbose_name='Cena (Stříbrňáky)')),
                ('weight', models.FloatField(default=0.0, verbose_name='Váha (libry)')),
                ('damage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poškození (Kostky a typ)')),
                ('armor_class', models.IntegerField(blank=True, null=True, verbose_name='Obranné číslo (AC)')),
                ('properties', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vlastnosti zbraně')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Předmět z Kompendia',
                'verbose_name_plural': 'Předměty z Kompendia',
                'ordering': ['name_cz'],
            },
        ),
    ]
