# Generated by Django 6.0.5 on 2026-10-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0004_compendiummonster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items_Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_index', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='API Index')),
                ('name_cz', models.CharField(blank=True, max_length=150, null=True, verbose_name='Český název')),
                ('name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Anglický název')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategorie')),
                ('cost_gold', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cena (Zlaťáky)')),
                ('cost_silver', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cena (Stříbrňáky)')),
                ('weight', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Váha (libry)')),
                ('damage', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poškození (Kostky a typ)')),
                ('armor_class', models.IntegerField(blank=True, null=True, verbose_name='Obranné číslo (AC)')),
                ('properties', models.CharField(blank=True, max_length=255, null=True, verbose_name='Vlastnosti zbraně')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
            ],
            options={
                'verbose_name': 'Aktivní předmět',
                'verbose_name_plural': 'Aktivní předměty',
                'ordering': ['name_cz'],
            },
        ),
        migrations.CreateModel(
            name='Monsters_Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_index', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='API Index')),
                ('name_cz', models.CharField(blank=True, max_length=150, null=True, verbose_name='Český název')),
                ('name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Anglický název')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Velikost')),
                ('monster_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Typ nestvůry')),
                ('subtype', models.CharField(blank=True, max_length=100, null=True, verbose_name='Podtyp')),
                ('alignment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Přesvědčení')),
                ('armor_class', models.IntegerField(blank=True, null=True, verbose_name='Třída zbroje (AC)')),
                ('armor_desc', models.CharField(blank=True, max_length=150, null=True, verbose_name='Typ zbroje')),
                ('hit_points', models.IntegerField(blank=True, null=True, verbose_name='Životy (HP)')),
                ('hit_dice', models.CharField(blank=True, max_length=50, null=True, verbose_name='Kostky životů')),
                ('speed', models.CharField(blank=True, max_length=200, null=True, verbose_name='Rychlost')),
                ('strength', models.IntegerField(blank=True, default=10, null=True, verbose_name='Síla (STR)')),
                ('dexterity', models.IntegerField(blank=True, default=10, null=True, verbose_name='Obratnost (DEX)')),
                ('constitution', models.IntegerField(blank=True, default=10, null=True, verbose_name='Odolnost (CON)')),
                ('intelligence', models.IntegerField(blank=True, default=10, null=True, verbose_name='Inteligence (INT)')),
                ('wisdom', models.IntegerField(blank=True, default=10, null=True, verbose_name='Moudrost (WIS)')),
                ('charisma', models.IntegerField(blank=True, default=10, null=True, verbose_name='Charisma (CHA)')),
                ('saving_throws', models.CharField(blank=True, max_length=255, null=True, verbose_name='Záchranné hody')),
                ('skills', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dovednosti')),
                ('damage_vulnerabilities', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zranitelnosti')),
                ('damage_resistances', models.CharField(blank=True, max_length=255, null=True, verbose_name='Odolnosti')),
                ('damage_immunities', models.CharField(blank=True, max_length=255, null=True, verbose_name='Imunity vůči poškození')),
                ('condition_immunities', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stavové imunity')),
                ('senses', models.CharField(blank=True, max_length=255, null=True, verbose_name='Smysly')),
                ('languages', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jazyky')),
                ('challenge_rating', models.FloatField(blank=True, null=True, verbose_name='Nebezpečnost (CR)')),
                ('xp', models.IntegerField(blank=True, default=0, null=True, verbose_name='Zkušenosti (XP)')),
                ('proficiency_bonus', models.IntegerField(blank=True, default=2, null=True, verbose_name='Zdatnostní bonus')),
                ('special_abilities', models.TextField(blank=True, null=True, verbose_name='Zvláštní schopnosti')),
                ('actions', models.TextField(blank=True, null=True, verbose_name='Akce')),
                ('legendary_actions', models.TextField(blank=True, null=True, verbose_name='Legendární akce')),
                ('reactions', models.TextField(blank=True, null=True, verbose_name='Reakce')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('image_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL obrázku')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Původní JSON data')),
            ],
            options={
                'verbose_name': 'Nestvůra z Kompendia',
                'verbose_name_plural': 'Nestvůry z Kompendia',
                'ordering': ['challenge_rating', 'name_cz'],
            },
        ),
        migrations.RenameModel(
            old_name='CompendiumItem',
            new_name='Items_All_db',
        ),
        migrations.RenameModel(
            old_name='CompendiumMonster',
            new_name='Monsters_All_db',
        ),
    ]
