# Generated by Django 6.0.5 on 2026-10-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0005_items_active_monsters_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monsters_active',
            options={'ordering': ['challenge_rating', 'name_cz'], 'verbose_name': 'Aktivní nestvůra', 'verbose_name_plural': 'Aktivní nestvůry'},
        ),
    ]
