# Generated by Django 6.0.5 on 2026-10-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0006_alter_monsters_active_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsters_active',
            name='in_fight',
            field=models.BooleanField(default=False, verbose_name='V boji'),
        ),
        migrations.AddField(
            model_name='monsters_all_db',
            name='in_fight',
            field=models.BooleanField(default=False, verbose_name='V boji'),
        ),
    ]
