# Generated by Django 6.0.5 on 2026-10-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0007_monsters_active_in_fight_monsters_all_db_in_fight'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsters_active',
            name='current_hp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Aktuální životy (HP)'),
        ),
    ]
