# Generated by Django 6.0.5 on 2026-10-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0008_monsters_active_current_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsters_active',
            name='is_dead',
            field=models.BooleanField(default=False, verbose_name='Je mrtvý'),
        ),
    ]
