# Generated by Django 6.0.5 on 2026-10-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0009_monsters_active_is_dead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monsters_active',
            options={'ordering': ['is_dead', 'challenge_rating', 'name_cz'], 'verbose_name': 'Aktivní nestvůra', 'verbose_name_plural': 'Aktivní nestvůry'},
        ),
        migrations.AddField(
            model_name='monsters_active',
            name='loot_gold',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Zlaté mince (GP)'),
        ),
        migrations.AddField(
            model_name='monsters_active',
            name='loot_silver',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Stříbrné mince (SP)'),
        ),
    ]
