# Generated by Django 6.0.5 on 2026-10-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0010_alter_monsters_active_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monsters_active',
            name='loot_able',
            field=models.BooleanField(default=False, verbose_name='možnost lootit'),
        ),
    ]
