# Generated by Django 6.0.5 on 2026-10-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0011_monsters_active_loot_able'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='in_fight',
            field=models.BooleanField(default=False, verbose_name='V boji'),
        ),
        migrations.AddField(
            model_name='npc',
            name='is_dead',
            field=models.BooleanField(default=False, verbose_name='Je mrtvý'),
        ),
        migrations.AddField(
            model_name='npc',
            name='loot_able',
            field=models.BooleanField(default=False, verbose_name='možnost lootit'),
        ),
        migrations.AddField(
            model_name='npc',
            name='loot_gold',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Zlaté mince (GP)'),
        ),
        migrations.AddField(
            model_name='npc',
            name='loot_silver',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Stříbrné mince (SP)'),
        ),
        migrations.DeleteModel(
            name='NpcLoot',
        ),
    ]
