# Generated by Django 6.0.5 on 2026-10-05 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0012_npc_in_fight_npc_is_dead_npc_loot_able_npc_loot_gold_and_more'),
        ('player_site_app', '0006_char_info_in_fight'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_active',
            name='char_own',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='player_site_app.char_info', verbose_name='Vlastník (Postava)'),
        ),
        migrations.AlterField(
            model_name='items_active',
            name='api_index',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='API Index'),
        ),
    ]
