# Generated by Django 6.0.5 on 2026-10-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0013_items_active_char_own_alter_items_active_api_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverAllSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loging_active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('editing_active', models.BooleanField(default=True, verbose_name='Aktivní')),
            ],
        ),
    ]
