# Generated by Django 6.0.5 on 2026-10-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0014_overallsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overallsettings',
            options={'verbose_name': 'Globální nastavení', 'verbose_name_plural': 'Globální nastavení'},
        ),
        migrations.AlterField(
            model_name='overallsettings',
            name='editing_active',
            field=models.BooleanField(default=True, verbose_name='Editace aktivní'),
        ),
        migrations.AlterField(
            model_name='overallsettings',
            name='loging_active',
            field=models.BooleanField(default=True, verbose_name='Přihlašování aktivní'),
        ),
    ]
