# Generated by Django 6.0.5 on 2026-10-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0015_alter_overallsettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kronika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název')),
                ('category', models.CharField(choices=[('info', 'Info'), ('lore', 'Příběh')], default='info', max_length=50, verbose_name='Kategorie')),
                ('popis', models.TextField(verbose_name='Popis')),
                ('odkryto_hracum', models.BooleanField(default=False, verbose_name='Odkrýt hráčům')),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('datum_aktualizace', models.DateTimeField(auto_now=True, verbose_name='Datum aktualizace')),
            ],
            options={
                'verbose_name': 'Kronika',
                'verbose_name_plural': 'Kronika',
                'ordering': ['-datum_vytvoreni'],
            },
        ),
    ]
