# Generated by Django 6.0.5 on 2026-10-06 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm_site_app', '0016_kronika'),
        ('player_site_app', '0017_alter_char_info_alignment_alter_char_info_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spells_All_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_index', models.CharField(max_length=100, unique=True, verbose_name='API Index')),
                ('name_cz', models.CharField(max_length=150, verbose_name='Český název')),
                ('name_en', models.CharField(max_length=150, verbose_name='Anglický název')),
                ('level', models.IntegerField(default=0, verbose_name='Úroveň kouzla')),
                ('is_cantrip', models.BooleanField(default=False, verbose_name='Je trik')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='Magická škola (CZ)')),
                ('school_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Magická škola (EN)')),
                ('casting_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Doba vyvolání')),
                ('range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosah')),
                ('components', models.CharField(blank=True, max_length=100, null=True, verbose_name='Složky (V, S, M)')),
                ('material', models.TextField(blank=True, null=True, verbose_name='Materiální složka')),
                ('duration', models.CharField(blank=True, max_length=150, null=True, verbose_name='Trvání')),
                ('concentration', models.BooleanField(default=False, verbose_name='Soustředění')),
                ('ritual', models.BooleanField(default=False, verbose_name='Rituál')),
                ('attack_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Typ útoku')),
                ('damage_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Typ zranění')),
                ('damage_dice', models.CharField(blank=True, max_length=150, null=True, verbose_name='Kostky poškození')),
                ('saving_throw', models.CharField(blank=True, max_length=100, null=True, verbose_name='Záchranný hod')),
                ('heal_dice', models.CharField(blank=True, max_length=150, null=True, verbose_name='Léčení')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('higher_levels', models.TextField(blank=True, null=True, verbose_name='Na vyšších úrovních')),
                ('classes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Povolání (CZ)')),
                ('races', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rasy (CZ)')),
                ('backgrounds', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zázemí (CZ)')),
                ('icon', models.FileField(blank=True, default='spells/default_spell.jpg', null=True, upload_to='spells/icons/', verbose_name='Ikonka soubor')),
                ('icon_url', models.CharField(blank=True, default='/static/img/spells/default_spell.jpg', max_length=255, null=True, verbose_name='URL ikonky')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Původní JSON data')),
            ],
            options={
                'verbose_name': 'Kouzlo z Kompendia',
                'verbose_name_plural': 'Kouzla z Kompendia',
                'ordering': ['level', 'name_cz'],
            },
        ),
        migrations.CreateModel(
            name='Spells_Active',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_index', models.CharField(blank=True, max_length=100, null=True, verbose_name='API Index')),
                ('name_cz', models.CharField(max_length=150, verbose_name='Český název')),
                ('name_en', models.CharField(max_length=150, verbose_name='Anglický název')),
                ('level', models.IntegerField(default=0, verbose_name='Úroveň kouzla')),
                ('is_cantrip', models.BooleanField(default=False, verbose_name='Je trik')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='Magická škola (CZ)')),
                ('school_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Magická škola (EN)')),
                ('casting_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Doba vyvolání')),
                ('range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosah')),
                ('components', models.CharField(blank=True, max_length=100, null=True, verbose_name='Složky (V, S, M)')),
                ('material', models.TextField(blank=True, null=True, verbose_name='Materiální složka')),
                ('duration', models.CharField(blank=True, max_length=150, null=True, verbose_name='Trvání')),
                ('concentration', models.BooleanField(default=False, verbose_name='Soustředění')),
                ('ritual', models.BooleanField(default=False, verbose_name='Rituál')),
                ('attack_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Typ útoku')),
                ('damage_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Typ zranění')),
                ('damage_dice', models.CharField(blank=True, max_length=150, null=True, verbose_name='Kostky poškození')),
                ('saving_throw', models.CharField(blank=True, max_length=100, null=True, verbose_name='Záchranný hod')),
                ('heal_dice', models.CharField(blank=True, max_length=150, null=True, verbose_name='Léčení')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Popis')),
                ('higher_levels', models.TextField(blank=True, null=True, verbose_name='Na vyšších úrovních')),
                ('classes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Povolání (CZ)')),
                ('races', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rasy (CZ)')),
                ('backgrounds', models.CharField(blank=True, max_length=255, null=True, verbose_name='Zázemí (CZ)')),
                ('icon', models.FileField(blank=True, default='spells/default_spell.jpg', null=True, upload_to='spells/icons/', verbose_name='Ikonka soubor')),
                ('icon_url', models.CharField(blank=True, default='/static/img/spells/default_spell.jpg', max_length=255, null=True, verbose_name='URL ikonky')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Původní JSON data')),
                ('nauceno', models.BooleanField(default=False, verbose_name='Naučeno')),
                ('vybaveno', models.BooleanField(default=False, verbose_name='Vybaveno')),
                ('char_own', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spells_active', to='player_site_app.char_info', verbose_name='Vlastník (Postava)')),
                ('template_spell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_instances', to='dm_site_app.spells_all_db', verbose_name='Šablona kouzla')),
            ],
            options={
                'verbose_name': 'Aktivní kouzlo postavy',
                'verbose_name_plural': 'Aktivní kouzla postav',
                'ordering': ['level', 'name_cz'],
            },
        ),
    ]
