# Generated by Django 6.0.5 on 2026-09-28 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Přezdívka hráče')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='O hráči')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum registrace')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='Uživatelský účet')),
            ],
            options={
                'verbose_name': 'Hráč',
                'verbose_name_plural': 'Hráči',
            },
        ),
        migrations.CreateModel(
            name='Char_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jméno postavy')),
                ('race', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rasa')),
                ('character_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Povolání')),
                ('level', models.IntegerField(default=1, verbose_name='Úroveň')),
                ('background', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zázemí')),
                ('alignment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Přesvědčení')),
                ('experience_points', models.IntegerField(default=0, verbose_name='Zkušenosti (XP)')),
                ('armor_class', models.IntegerField(default=10, verbose_name='Třída zbroje (AC)')),
                ('hit_points_max', models.IntegerField(default=10, verbose_name='Maximální životy')),
                ('hit_points_current', models.IntegerField(default=10, verbose_name='Současné životy')),
                ('speed', models.IntegerField(default=30, verbose_name='Rychlost (stopy)')),
                ('strength', models.IntegerField(default=10, verbose_name='Síla (STR)')),
                ('dexterity', models.IntegerField(default=10, verbose_name='Obratnost (DEX)')),
                ('constitution', models.IntegerField(default=10, verbose_name='Odolnost (CON)')),
                ('intelligence', models.IntegerField(default=10, verbose_name='Inteligence (INT)')),
                ('wisdom', models.IntegerField(default=10, verbose_name='Moudrost (WIS)')),
                ('charisma', models.IntegerField(default=10, verbose_name='Charisma (CHA)')),
                ('backstory', models.TextField(blank=True, null=True, verbose_name='Příběh postavy')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Poznámky')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Poslední úprava')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='player_site_app.player', verbose_name='Hráč')),
            ],
            options={
                'verbose_name': 'Postava hráče',
                'verbose_name_plural': 'Postavy hráče',
                'ordering': ['-level', 'name'],
            },
        ),
    ]
