# Generated by Django 6.0.5 on 2026-09-29 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivements_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Jméno úspěchu')),
                ('description', models.CharField(max_length=200, verbose_name='Popis úspěchu')),
                ('bronze_value', models.FloatField(blank=True, default=0, null=True, verbose_name='hodnota pro bronze')),
                ('silver_value', models.FloatField(blank=True, default=0, null=True, verbose_name='hodnota pro silver')),
                ('gold_value', models.FloatField(blank=True, default=0, null=True, verbose_name='hodnota pro gold')),
                ('platinum_value', models.FloatField(blank=True, default=0, null=True, verbose_name='hodnota pro platinum')),
                ('emerald_value', models.FloatField(blank=True, default=0, null=True, verbose_name='hodnota pro emerald')),
                ('diamond_value', models.FloatField(blank=True, default=0, null=True, verbose_name='hodnota pro diamond')),
            ],
        ),
        migrations.CreateModel(
            name='Char_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jméno postavy')),
                ('race', models.CharField(blank=True, max_length=50, null=True, verbose_name='Rasa')),
                ('character_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Povolání')),
                ('level', models.IntegerField(default=1, verbose_name='Úroveň')),
                ('background', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zázemí')),
                ('alignment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Přesvědčení')),
                ('experience_points', models.IntegerField(default=0, verbose_name='Zkušenosti (XP)')),
                ('gold', models.IntegerField(blank=True, default=0, null=True, verbose_name='Zlaťáky')),
                ('silver', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stříbráky')),
                ('total_golds', models.FloatField(blank=True, default=0, null=True, verbose_name='Celkové zlaťáky - EVER')),
                ('armor_class', models.IntegerField(default=10, verbose_name='Třída zbroje (AC)')),
                ('hit_points_max', models.IntegerField(default=10, verbose_name='Maximální životy')),
                ('hit_points_current', models.IntegerField(default=10, verbose_name='Současné životy')),
                ('speed', models.IntegerField(default=30, verbose_name='Rychlost (stopy)')),
                ('strength', models.IntegerField(default=10, verbose_name='Síla (STR)')),
                ('dexterity', models.IntegerField(default=10, verbose_name='Obratnost (DEX)')),
                ('constitution', models.IntegerField(default=10, verbose_name='Odolnost (CON)')),
                ('intelligence', models.IntegerField(default=10, verbose_name='Inteligence (INT)')),
                ('wisdom', models.IntegerField(default=10, verbose_name='Moudrost (WIS)')),
                ('charisma', models.IntegerField(default=10, verbose_name='Charisma (CHA)')),
                ('backstory', models.TextField(blank=True, null=True, verbose_name='Příběh postavy')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Poznámky')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Poslední úprava')),
            ],
            options={
                'verbose_name': 'Postava hráče',
                'verbose_name_plural': 'Postavy hráče',
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Přezdívka hráče')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='O hráči')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum registrace')),
                ('temna_esence', models.IntegerField(blank=True, default=0, null=True, verbose_name='Temná esence')),
                ('pin_code', models.IntegerField(blank=True, default=0, null=True, verbose_name='Pin kod')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='Uživatelský účet')),
            ],
            options={
                'verbose_name': 'Hráč',
                'verbose_name_plural': 'Hráči',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='Zpráva')),
                ('value', models.FloatField(blank=True, default=0, null=True, verbose_name='Hodnota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='player_site_app.char_info', verbose_name='Postava')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='player_site_app.player', verbose_name='Hráč')),
            ],
        ),
        migrations.AddField(
            model_name='char_info',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='player_site_app.player', verbose_name='Hráč'),
        ),
        migrations.CreateModel(
            name='Achivements_players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('emerald', 'Emerald'), ('diamond', 'Diamond')], max_length=20, null=True, verbose_name='Aktuální status')),
                ('current_value', models.FloatField(default=0, verbose_name='Současná hodnota')),
                ('bronze_obtained_date', models.DateTimeField(blank=True, null=True, verbose_name='Datum získání bronze')),
                ('silver_obtained_date', models.DateTimeField(blank=True, null=True, verbose_name='Datum získání silver')),
                ('gold_obtained_date', models.DateTimeField(blank=True, null=True, verbose_name='Datum získání gold')),
                ('platinum_obtained_date', models.DateTimeField(blank=True, null=True, verbose_name='Datum získání platinum')),
                ('emerald_obtained_date', models.DateTimeField(blank=True, null=True, verbose_name='Datum získání emerald')),
                ('diamond_obtained_date', models.DateTimeField(blank=True, null=True, verbose_name='Datum získání diamond')),
                ('Achivement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achivements', to='player_site_app.achivements_database', verbose_name='Achivement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achivements', to='player_site_app.player', verbose_name='Hráč')),
            ],
        ),
    ]
