# Generated by Django 6.0.5 on 2026-09-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivements_database',
            name='img_ozn',
            field=models.CharField(blank=True, default='PRÁZDNO', max_length=50, null=True, verbose_name='Označení ikonky'),
        ),
    ]
