# Generated by Django 6.0.5 on 2026-09-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='char_info',
            name='gold',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Zlaťáky'),
        ),
        migrations.AddField(
            model_name='char_info',
            name='silver',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Stříbráky'),
        ),
        migrations.AddField(
            model_name='player',
            name='pin_code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pin kod'),
        ),
        migrations.AddField(
            model_name='player',
            name='temna_esence',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Temná esence'),
        ),
    ]
