# Generated by Django 6.0.5 on 2026-09-29 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0002_achivements_database_img_ozn'),
    ]

    operations = [
        migrations.AddField(
            model_name='achivements_players',
            name='char',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achivements', to='player_site_app.char_info', verbose_name='Postava'),
        ),
        migrations.AlterField(
            model_name='achivements_players',
            name='Achivement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achivements', to='player_site_app.achivements_database', verbose_name='Achivement'),
        ),
        migrations.AlterField(
            model_name='achivements_players',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achivements', to='player_site_app.player', verbose_name='Hráč'),
        ),
    ]
