# Generated by Django 6.0.5 on 2026-09-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0003_achivements_players_char_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='admin',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Jsi administrátor'),
        ),
    ]
