# Generated by Django 6.0.5 on 2026-09-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0004_player_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achivements_database',
            options={'verbose_name': 'Úspěch (šablona)', 'verbose_name_plural': 'Úspěchy (šablony)'},
        ),
        migrations.AlterModelOptions(
            name='achivements_players',
            options={'ordering': ['-current_value', 'Achivement'], 'verbose_name': 'Úspěch hráče', 'verbose_name_plural': 'Úspěchy hráčů'},
        ),
    ]
