# Generated by Django 6.0.5 on 2026-10-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0005_alter_achivements_database_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='char_info',
            name='in_fight',
            field=models.BooleanField(default=False, verbose_name='V boji'),
        ),
    ]
