# Generated by Django 6.0.5 on 2026-10-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0006_char_info_in_fight'),
    ]

    operations = [
        migrations.AddField(
            model_name='char_info',
            name='image',
            field=models.FileField(blank=True, default='characters/default_avatar.jpg', null=True, upload_to='characters/', verbose_name='Profilový obrázek'),
        ),
        migrations.AddField(
            model_name='char_info',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Externí URL profilového obrázku'),
        ),
    ]
