# Generated by Django 6.0.5 on 2026-10-05 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0007_char_info_image_char_info_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esence_Items_Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('category', models.CharField(choices=[('borders', 'Rámečky'), ('backgrounds', 'Pozadí')], max_length=100, verbose_name='Kategorie')),
                ('image', models.FileField(upload_to='esence_items', verbose_name='Obrázek')),
                ('cost', models.IntegerField(default=0, verbose_name='Cena')),
            ],
        ),
        migrations.CreateModel(
            name='Esence_Items_Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esence_items', to='player_site_app.player', verbose_name='Hráč')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esence_items', to='player_site_app.esence_items_shop', verbose_name='Předmět')),
            ],
        ),
    ]
