# Generated by Django 6.0.5 on 2026-10-05 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0008_esence_items_shop_esence_items_owners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='esence_items_owners',
            options={'verbose_name': 'Vlastněný předmět z Esence Shopu', 'verbose_name_plural': 'Vlastněné předměty z Esence Shopu'},
        ),
        migrations.AddField(
            model_name='player',
            name='active_ramecek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_in_players', to='player_site_app.esence_items_owners', verbose_name='Aktivní rámeček'),
        ),
    ]
