# Generated by Django 6.0.5 on 2026-10-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0009_alter_esence_items_owners_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esence_items_shop',
            name='cost',
        ),
        migrations.AddField(
            model_name='esence_items_shop',
            name='rarity',
            field=models.CharField(choices=[('basic', 'Běžná'), ('rare', 'Vzácná'), ('epic', 'Epická'), ('legendary', 'Legendární')], default='basic', max_length=100, verbose_name='Rarita'),
        ),
    ]
