# Generated by Django 6.0.5 on 2026-10-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0010_remove_esence_items_shop_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esence_items_shop',
            name='category',
            field=models.CharField(choices=[('borders', 'Rámečky'), ('backgrounds', 'Pozadí'), ('treasures', 'Truhly')], max_length=100, verbose_name='Kategorie'),
        ),
    ]
