# Generated by Django 6.0.5 on 2026-10-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0011_alter_esence_items_shop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='esence_items_shop',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cena'),
        ),
    ]
