# Generated by Django 6.0.5 on 2026-10-06 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0012_esence_items_shop_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='char_info',
            name='backstory',
        ),
        migrations.RemoveField(
            model_name='char_info',
            name='notes',
        ),
        migrations.CreateModel(
            name='CharBackstory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backstory', models.TextField(verbose_name='Příběh postavy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
                ('public', models.BooleanField(default=False, verbose_name='Veřejné')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_backstories', to='player_site_app.char_info', verbose_name='Postava')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backstories', to='player_site_app.player', verbose_name='Hráč')),
            ],
            options={
                'verbose_name': 'Příběh postavy',
                'verbose_name_plural': 'Příběhy postav',
            },
        ),
        migrations.CreateModel(
            name='CharNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(verbose_name='Poznámka')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char_notes', to='player_site_app.char_info', verbose_name='Postava')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='player_site_app.player', verbose_name='Hráč')),
            ],
            options={
                'verbose_name': 'Poznámka hráče',
                'verbose_name_plural': 'Poznámky hráčů',
            },
        ),
    ]
