# Generated by Django 6.0.5 on 2026-10-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0013_remove_char_info_backstory_remove_char_info_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char_info',
            name='character_class',
            field=models.CharField(blank=True, choices=[('Barbar', 'Barbar'), ('Bard', 'Bard'), ('Bojovník', 'Bojovník'), ('Čaroděj', 'Čaroděj'), ('Černokněžník', 'Černokněžník'), ('Druid', 'Druid'), ('Hraničář', 'Hraničář'), ('Klerik', 'Klerik'), ('Kouzelník', 'Kouzelník'), ('Mnich', 'Mnich'), ('Paladin', 'Paladin'), ('Tulák', 'Tulák'), ('Ostatní', 'Ostatní')], default='Ostatní', max_length=50, null=True, verbose_name='Povolání'),
        ),
        migrations.AlterField(
            model_name='char_info',
            name='race',
            field=models.CharField(blank=True, choices=[('Člověk', 'Člověk'), ('Elf', 'Elf'), ('Hobit', 'Hobit'), ('Trpaslík', 'Trpaslík'), ('Drakorozený', 'Drakorozený'), ('Gnom', 'Gnom'), ('Půlelf', 'Půlelf'), ('Půlork', 'Půlork'), ('Tiefling', 'Tiefling'), ('Ostatní', 'Ostatní')], default='Ostatní', max_length=50, null=True, verbose_name='Rasa'),
        ),
    ]
