# Generated by Django 6.0.5 on 2026-10-06 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0014_alter_char_info_character_class_alter_char_info_race'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pin_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='PIN kód'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL, verbose_name='Uživatelský účet'),
        ),
    ]
