# Generated by Django 6.0.5 on 2026-10-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0015_alter_player_pin_code_alter_player_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charbackstory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Příběh postavy', 'verbose_name_plural': 'Příběhy postav'},
        ),
        migrations.AlterModelOptions(
            name='charnotes',
            options={'ordering': ['-is_favorite', '-updated_at'], 'verbose_name': 'Poznámka hráče', 'verbose_name_plural': 'Poznámky hráčů'},
        ),
        migrations.AddField(
            model_name='charbackstory',
            name='title',
            field=models.CharField(default='Kapitola příběhu', max_length=200, verbose_name='Název zápisu'),
        ),
        migrations.AddField(
            model_name='charnotes',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Oblíbená poznámka'),
        ),
        migrations.AddField(
            model_name='charnotes',
            name='title',
            field=models.CharField(default='Nová poznámka', max_length=200, verbose_name='Název poznámky'),
        ),
        migrations.AlterField(
            model_name='charbackstory',
            name='public',
            field=models.BooleanField(default=False, verbose_name='Veřejné pro ostatní hráče'),
        ),
        migrations.AlterField(
            model_name='charnotes',
            name='note',
            field=models.TextField(verbose_name='Text poznámky'),
        ),
    ]
