# Generated by Django 6.0.5 on 2026-10-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player_site_app', '0016_alter_charbackstory_options_alter_charnotes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char_info',
            name='alignment',
            field=models.CharField(blank=True, choices=[('Zákonně dobrý', 'Zákonně dobrý'), ('Chaoticky dobrý', 'Chaoticky dobrý'), ('Neutrální dobrý', 'Neutrální dobrý'), ('Zákonně neutrální', 'Zákonně neutrální'), ('Neutrální', 'Neutrální'), ('Chaoticky neutrální', 'Chaoticky neutrální'), ('Zákonně zlý', 'Zákonně zlý'), ('Neutrálně zlý', 'Neutrálně zlý'), ('Chaoticky zlý', 'Chaoticky zlý'), ('Ostatní', 'Ostatní')], max_length=50, null=True, verbose_name='Přesvědčení'),
        ),
        migrations.AlterField(
            model_name='char_info',
            name='background',
            field=models.CharField(blank=True, choices=[('Akolyta', 'Akolyta'), ('Bavič', 'Bavič'), ('Cechovní řemeslník', 'Cechovní řemeslník'), ('Hlídkař', 'Hlídkař'), ('Lidový hrdina', 'Lidový hrdina'), ('Mudrc', 'Mudrc'), ('Námořník', 'námořník'), ('Poustevník', 'poustevník'), ('Šlechtic', 'Šlechtic'), ('Šarlatán', 'šarlatán'), ('Uličník', 'uličník'), ('Voják', 'Voják'), ('Zločinec', 'Zločinec'), ('Ostatní', 'ostatní')], max_length=100, null=True, verbose_name='Zázemí'),
        ),
    ]
